# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "venmo-http"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karen Kelley"]
  s.date = "2016-05-24"
  s.description = "Gem using http to post to Venmo payment gateway"
  s.email = "karenkelley11@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/generators/install_generator.rb",
    "lib/generators/templates/venmo_initalizer.rb",
    "lib/tasks/venmo_tasks.rake",
    "lib/venmo.rb",
    "lib/venmo/config.rb",
    "lib/venmo/pay.rb",
    "lib/venmo/sender.rb",
    "venmo.gemspec"
  ]
  s.homepage = "http://github.com/kkelleey/venmo"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Gem to integrate with Venmo payment services"

  s.add_development_dependency "rspec"
  s.add_development_dependency "vcr"
  s.add_development_dependency "webmock"

  s.add_dependency "faraday"
  s.add_dependency "json"
end
